#Comment: Student record
#Describes some characteristics and preferences
---
images:
  LayoutFolderPath: "../New folder"

LayoutGan:
  TrainTestSplit: 0.75
  ImgSize: [64,64,3]
  ImageSuffleSeed: -1 # -1 to enable random shuffle
  

name: Martin D'vloper #key-value
age: 26
hobbies: 
  - painting #first list item
  - playing_music #second list item
  - cooking #third list item
programming_languages:
  java: Intermediate
  python: Advanced
  javascript: Beginner
favorite_food: 
  - vegetables: tomatoes 
  - fruits: 
      citrics: oranges 
      tropical: bananas
      nuts: peanuts
      sweets: raisins