#Comment: Student record
#Describes some characteristics and preferences
---
images:
  Dataset: 'D:\\uni\\Thesis\\New folder\\dataset2' #windows
  #Dataset: '/home/roterex/thesis/dataset2' #wsl
  Epochs: 0
  plotSample: False

LayoutGan:
  TrainTestSplit: 0.75
  ImageSuffleSeed: -1 # -1 to enable random shuffle
  ImgSize: [64,64,3]
  BatchSize: 64
  BufferSize: 400

Loss:
  Loss_function: 'cross' #cross, wesser

Checkpoint:
  plot_checkpoints: True
  save_every: 5000
  save_dir: './training_checkpoints_ds2_C'
  load_dir: './New folder'
  load_from_checkpoint: True
  checkpoint_to_load: 'ckpt-8' #leave empty for latest

PostProcess:


Waz:
  a: 0.00005 #learning rate - not imp
  c: 0.01 #clipping param - not imp
  ncrit: 5 #critic updates per generator update - not imp