#Comment: Student record
#Describes some characteristics and preferences
---
images:
  #Dataset: 'D:\\uni\\Thesis\\New folder\\dataset2' #windows
  Dataset: '/home/roterex/data/dataset2' #wsl
  Epochs: 10000
  plotSample: False

LayoutGan:
  TrainTestSplit: 0.75
  ImageSuffleSeed: -1 # -1 to enable random shuffle
  ImgSize: [64,64,3]
  BatchSize: 64
  BufferSize: 400

Loss:
  Loss_function: 'cross' #cross, wesser

Checkpoint:
  plot_checkpoints: False
  save_every: 5000
  save_dir: './training_checkpoints_ds2_C'
  load_dir: '../training_checkpoints_ds2_wes_2'
  load_from_checkpoint: False
  checkpoint_to_load: '' #leave empty for latest

PostProcess:


Waz:
  a: 0.00005 #learning rate - not imp
  c: 0.01 #clipping param - not imp
  ncrit: 5 #critic updates per generator update - not imp